### ISSUE TITLE
Package Download Issue

### ISSUE THREAD

**Issue by erin-d** [mikemc/speedyseq#28]
Hi, I am having issues installing this package. I have installed the packages remotes and used the call ‘remotes::install_github("mikemc/speedyseq”)’ to download. I have R version 3.5.2 and phyloseq version 1.26.1

I get the following error:

* installing *source* package ‘speedyseq’ ...
** R
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for ‘phyloseq’:
 (converted from warning) no function found corresponding to methods exports from ‘XVector’ for: ‘concatenateObjects’
Error : package ‘phyloseq’ could not be loaded
ERROR: lazy loading failed for package ‘speedyseq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/speedyseq’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/bk/dmszvjc51jsfs3b5n25znglw0000gn/T//Rtmp3pbqTD/filee3e17f0cdcf2/speedyseq_0.1.2.9004.tar.gz’ had non-zero exit status

Do you have any insight into this error to help me resolve it or is there another way to install this package?

**Comment by mikemc** [comment]
Hi @erin-d, can you confirm that you are able to load phyloseq with `library(phyloseq)` without any errors? If not, then getting that fixed by reinstalling phyloseq (may require reinstalling dependencies like vegan as well) so that you are able to load phyloseq should do the trick. Otherwise I will try to see if I'm able to install speedyseq on R 3.5.1 tomorrow (this is an older R and phyloseq version than what I've tested with recently)

**Comment by mikemc** [comment]
I was able to successfully install Bioconductor 3.8, phyloseq 1.26.1, and the lastest speedyseq in R 3.5.1 on our Ubuntu Linux server, so I suspect this is an issue with your phyloseq install getting messed up after some package updates or something similar and will hopefully be fixed if you can reinstall phyloseq.

**Comment by erin-d** [comment]
Thank you! Its seem to work now after reinstallation of phyloseq!
