### ISSUE TITLE
Segfault memory issue on cluster

### ISSUE THREAD

**Issue by ptpell77** [mikemc/speedyseq#59]
Hi Mike,

I'm trying to use merge_taxa_vec command on a very large phyloseq object (1.5 million ASV by 8k samples). I've clustered OTU in vsearch and attempting to collapse the phyoseq object with your command. I get the following error using 200Gb RAM on a unix cluster, running R 4.0.2

 *** caught segfault ***
address 0x7f4baffff340, cause 'memory not mapped'

Traceback:
 1: rowsum.default(x, group, reorder = reorder)
 2: rowsum(x, group, reorder = reorder)
 3: otu_table(rowsum(x, group, reorder = reorder), taxa_are_rows = TRUE)
 4: .local(x, group, reorder)
 5: merge_taxa_vec(otu_table(x), group, reorder = reorder)
 6: merge_taxa_vec(otu_table(x), group, reorder = reorder)
 7: speedyseq::merge_taxa_vec(filtered_vsearch_ASV, group = u.c.vsearch.2.hits$OTU,     tax_adjust = 0)
 8: speedyseq::merge_taxa_vec(filtered_vsearch_ASV, group = u.c.vsearch.2.hits$OTU,     tax_adjust = 0)
An irrecoverable exception occurred. R is aborting now ...

**Comment by mikemc** [comment]
Hi @ptpell77, thanks for raising this issue. Can you confirm that the command works when you first subset to e.g. just the first 10000 ASVs? Your use case of 1.5 million ASVs is orders of magnitude beyond what I've even imagined using speedyseq or phyloseq for and if this is an issue that only occurs with such extremely large matrices then it will be hard for me to figure out what is going on here. If the issue is with `base::rowsum()` there isn't much I can do about it. You might look into alternative data structures (like sparse matrices in the Matrix package) or packages to see if there is an equivalent of `rowsum()` that can work on larger matrices.

What is your application? I'm wondering why you have such an extremely large number of ASVs. Perhaps most of these ASVs are extreme rare or low prevalence and could be removed by filtering prior to attempting the merge? That might reduce the matrix to a workable size.

**Comment by ptpell77** [comment]
Thanks for your insights here. I have confirmed that it works on both my local computer and the cluster with 10,000 ASV, almost instantly. 

The very large number of ASV represents a continental scale sampling effort for fungi. It is true that many of them are very rare, but without knowing the underlying distribution of ASV in the OTU, removing singleton ASV could be be less than ideal. Is it possible to run speedyseq on an older R package? The folks at the cluster recommended this due to potential incompatibilities?

**Comment by mikemc** [comment]
Since filtering very low read count ASVs might solve your problem, I'll offer an alternative opinion about singletons: I personally would be very worried that ASVs that appear in just one sample or in a very low number of total reads are mostly artefacts of sequencing or contamination. Although I know it is useful to know true biological singletons for species richness analysis, I don't think amplicon sequencing is a trustworthy source of that information.

As far as trying to run speedyseq on an older R version, you could try that though I don't really recommend this option unless you find a source of information that suggests `base::rowsum()` would work on larger matrices in older R versions. I have not carefully determined the minimum package versions needed for speedyseq dependencies, but older versions of R and most packages should mostly be ok. Since the problem here seems to be with the rowsum operation, the simplest way to test this solution would be to see if you can use rowsum on your matrix in the older R version. That way you remove the complications of all the other speedyseq dependencies. If rowsum won't work, then merge_taxa_vec won't work, and you'll need to look for another option.

Your best option if you really need to do a merge on the full matrix might be to look for other matrix classes and packages (e.g. the sparse matrix types in the Matrix package) and see if they can handle merging. The sparse matrix types might have a much lower memory usage for your use case. Unfortunately phyloseq can only use standard R matrices, so you can't use these with speedyseq. And perhaps more to the point, I don't know if there is an equivalent to `base::rowsum()` that works on these alternative matrix types. But you might be able to do the merge operation manually using sparse matrices and then import back into phyloseq

**Comment by mikemc** [comment]
It looks like there are indeed some options available for fast aggregation of rows on sparse matrices, for example with the method described in https://slowkow.com/notes/sparse-matrix/ for sparse matrices from the Matrix package or using the [DelayedArray](http://bioconductor.org/packages/release/bioc/html/DelayedArray.html) package (which it looks like provides a `rowsum()` operation for matrices stored on disk and perhaps also sparse matrices from Matrix). You might give these approaches a shot; the DelayedArray option might be the way to go if you don't want to read the huge matrix into memory in the first place.

I may not get around to trying these out until next weekend. Once I figure them out will post some code here may add an option to `merge_taxa_vec()` that would do the merging by converting the matrix to a sparse matrix just for the merging, and then convert back to a dense matrix so that a phyloseq object can be returned.

**Comment by mikemc** [comment]
I tried out both of the above methods and think either could work for your situation. I'm assuming your matrix is actually sparse in the sense of most entries being 0. 

I fleshed out an example of the first approach, using a sparse matrix from the Matrix package, [here](https://stackoverflow.com/questions/51025979/equivalent-of-rowsum-function-for-matrix-class-dgcmatrix/66539129#66539129).  If you already have your data as a phyloseq object, you'd need to first create a sparse-matrix version of your otu table,
```r
library(Matrix)
library(phyloesq)

data(GlobalPatterns)

m <- as(otu_table(GlobalPatterns), "sparseMatrix")
```

But it makes more sense to load your data as a sparse matrix, do the merging, then convert to a standard (dense) matrix for phyloseq, since the sparse matrix in your case should use much less memory than the equivalent dense matrix assuming the data actually is sparse, and once the merging is done your matrix will be (much) smaller and more suited for treating as a dense matrix. Similarly, if you use the DelayedArray approach you would be better off not creating a dense matrix until after you've done the merging. I would look into reading your saved data directly into sparse matrices, or using DelayedArray's functionality for working with on-disk matrices until you've done your merging, then create your phyloseq object for downstream analysis. 

The main remaining difficulty is that you still need to manually create the new tax table, tree, and refseq objects. You could do this by calling `merge_taxa_vec()` on each of these components individually. When you do this, the new OTUs will be named according to the first taxon in each group. So you should make sure that these OTUs are used as your "group" variable when you do the matrix merging operation and so end up as the new matrix row names. Then all the new objects will have matching taxa names and can be joined into a phyloseq object.

It would be useful to have an extension of the phyloseq class that can use sparse matrices, that would support doing operations like `merge_taxa_vec()` just as in standard phyloseq objects from the user's perspective, but this is not something I am likely to have time to implement any time soon.

**Comment by ptpell77** [comment]
Thanks Mike for going above and beyond
